### ISSUE TITLE
Light Problem

### ISSUE THREAD

**Issue by 1Example** [Vadya963/MTA-map_mafia2#5]
Hello, first i would like to thank you so much for your work and this amazing project. If there are some ways i can support you or show you my appreciation please let me know. 
I'm trying to get some lights working on this map but i can't not succeed. 
Due to GTA SA limitations from what i understood we can get lights to work on custom maps only with the help of shaders so in this case with MTA shaders.
I'm trying this one: https://community.mtasa.com/index.php?p=resources&s=details&id=15978 but everytime my MTA crashes. 
Also from time to time when connecting to the server using your custom map the MTA client crashes because of the following objects ids:
809
856
1485
5532
2287
4042

**Comment by Vadya963** [comment]
I know about the crashes, but I don't know how to fix them

**Comment by Vadya963** [comment]
if you load one area where there are these objects, they do not break the game, probably the more objects are replaced, the more departures

**Comment by Vadya963** [comment]
the problem with the lighting is related to the MTA itself
https://github.com/multitheftauto/mtasa-blue/issues/450
