### ISSUE TITLE
Один вопрос

### ISSUE THREAD

**Issue by KostyanSigaev** [Vadya963/MTA-map_mafia2#7]
Я тут недавно смог портировать всю карту GTA SS на Unity, и у меня появилась идея портировать карту Mafia 2 из MTA, т.к я уже больше чем пол года пользуюсь данным проектом. Вопрос: Вы разрешаете мне возпользоваться дангым проектом для неофициального порта Mafia 2 на unity для дальнейших портов на Windows, Linux, Android и т.п.?

**Comment by Vadya963** [comment]
да

**Comment by KostyanSigaev** [comment]
Спасибо
