### ISSUE TITLE
Снова проблемка

### ISSUE THREAD

**Issue by KostyanSigaev** [Vadya963/MTA-map_mafia2#8]
Я тут наткнулся на проблему: твой .ipl файл слишком большой и у меня 3ds max просто не справляется с ним... Я пытался разбить его на несколько иплов, даже плрайонно делил, но в таком случае 3ds max попросту не открывает их, так я вошел в безвыходное положение... Ты можешь сам разбить его на несколько файлов, а то у меня, видимо, руки не из того места растут...
Кстати насчёт ошибки при открытии карты целиком: общий вес всех .dff выходит больше 1,5 гб, (+ в ipl некоторые модели дублируются по несколько раз, в общем счёте выходит около 3-х гб) у меня же всего 2 гб озу, вот макс и ругается на недостаток оперативной памяти...

**Comment by Vadya963** [comment]
когда я вырезал район, и открывал его, всё работало

**Comment by Vadya963** [comment]
а ide не надо делить?

**Comment by KostyanSigaev** [comment]
ide вроде как нет... Ну по крайней мере, когда я делал конверт карты Сосновка из fs 17, я все id записал в один ide, сами же объекты раскидал по группам (doma.ipl, dorogi.ipl, landshaft.ipl и т.п.), но, к сожалению, жестких диск с этим проетом сдох...

**Comment by Vadya963** [comment]
я разделил, они в папке map_mafia2_pos -> areas
